### ISSUE TITLE
Send issue

### ISSUE THREAD

**Issue by thanosalexander** [infobip/infobip-api-php-client#1]
I try to send a multiple sms with  SendMultipleTextualSmsAdvanced client and SMSAdvancedTextualRequest but i received this
Exception in AbstractApiClient.php line 124:
{"requestError":{"serviceException":{"messageId":"BAD_REQUEST","text":"Bad request"}}}

I was only able to send with SendSingleTextualSms in 1 number..
But i need the SendMultipleTextualSmsAdvanced,SendMultipleSmsBinaryAdvanced in order to cover all sms types(text,binary,flash,wap)!

**Comment by nmenkovic-ib** [comment]
Hi,

It seems like you didn't use **destinations** or **messages** properly. I advise you to check out the [library examples](https://github.com/infobip/infobip-api-php-client/tree/master/infobip/examples), as they can be helpful.


Kind regards,
Nevena
