### ISSUE TITLE
Voice API?

### ISSUE THREAD

**Issue by evgenivanov90** [infobip/infobip-api-php-client#11]
Is the way to send Speech2Voice via this PHP package?

**Comment by leonbda** [comment]
Hi, we are expecting to have a new version of VOICE API in couple of weeks and we plan to add it to library then.

**Comment by Azakur4** [comment]
some news about this??

**Comment by leonbda** [comment]
Hi! New version of Voice API is out now. You can find documentation here: https://dev.infobip.com/docs/tts-introduction

This update is still not included in php client but it's on our to do list. ETA, hopefully November.

**Comment by andela-sakande** [comment]
It's November 2017, How soon can the Voice API be a part of this package?

**Comment by Antolius** [comment]
Hi! Our Voice team has been busy, and unfortunately adding official support for their API to this client has been pushed back into the next year.

In the meantime I'd encourage you to use this repository as a starting point and tweak it to your own needs. You can fork it and add support or any additional API endpoints (voice included).
