### ISSUE TITLE
REJECTED_SOURCE

### ISSUE THREAD

**Issue by PurityMaina** [infobip/infobip-api-php-client#12]
Message ID: c97**_cc56 Receiver: 25**_**20 Message status: REJECTED_SOURCE.

I get the above error, please help figure out why

**Comment by leonbda** [comment]
Hi Sherry,

Thank you for your input.

It seems the error is related to the message status itself, which is something our Support team will be able to assist further. I can see the request has been received and processed correctly, so for any similar errors, feel free to contact them either via email on support@infobip.com or Skype "infobip" for further assistance.

Hope this helps!

**Comment by SherryWaMaina** [comment]
Good morning Leon,
thank you for the help, let me reach out for assistance.
