### ISSUE TITLE
autoload.php can't be found..

### ISSUE THREAD

**Issue by motogashi** [infobip/infobip-api-php-client#14]
the autoload.php file after download, how can i fix this. thank you.

**Comment by maarekj** [comment]
What do you use `composer` ?

**Comment by jubairislam** [comment]
PHP

Thanks & Regards,
Md. Jubair Ahmed
Call: +8801775-879401 <%2B8801715019548>
Web: http://jubairislam.xyz <http://zoaddar.org>

**Comment by maarekj** [comment]
PHP ok, but to use `composer` is pre-required ([link to documentation](getcomposer.org) of composer).
Once composer installed, you can install this library with composer as indicated in the file README.md
When you run `composer install` or `composer update`, composer create an `autoload.php` file. The famous file that you can't found.

**Comment by motogashi** [comment]
OK thanks
