### ISSUE TITLE
Allow to use a proxy

### ISSUE THREAD

**Issue by Taluu** [infobip/infobip-api-php-client#15]
It seems that currently, we can't use a proxy with this lib, so we had to fork it a long time ago. Allowing to set it through the curl opt (`CURLOPT_PROXY`) could be a good start !

I could try to make a PR if you'd like.

Thanks.

**Comment by hkozacinski** [comment]
Hi Taluu!

Sorry for such a late reply. This repository is a starting point which can help you with your development, so forking and tweaking it to your own needs is something that is definitively encouraged.
A pull request regarding your issue sounds great. Please note that most of the content of this repository is auto-generated and our generation process would override any manual changes made in the pull request that affects the auto-generated part of the code.  However, your input will be validated and could be used and incorporated in the auto-generated process.

I wish you a Merry Christmas and a great holiday season that is before us!

**Comment by prodhan** [comment]
I have found this error:

Fatal error: Uncaught RuntimeException: SSL certificate problem: unable to get local issuer certificate in G:\webs\htdocs\smart\vendor\infobip\infobip-api-php-client\infobip\api\AbstractApiClient.php:118 Stack trace: #0 G:\webs\htdocs\smart\vendor\infobip\infobip-api-php-client\infobip\api\AbstractApiClient.php(23): infobip\api\AbstractApiClient->executeRequest('GET', 'https://api.inf...', Array) #1 G:\webs\htdocs\smart\vendor\infobip\infobip-api-php-client\infobip\api\client\GetAccountBalance.php(22): infobip\api\AbstractApiClient->executeGET('https://api.inf...', NULL) #2 G:\webs\htdocs\smart\sms.php(8): infobip\api\client\GetAccountBalance->execute() #3 {main} thrown in G:\webs\htdocs\smart\vendor\infobip\infobip-api-php-client\infobip\api\AbstractApiClient.php on line 118
