### ISSUE TITLE
How to send SMS to multiple numbers

### ISSUE THREAD

**Issue by bot101** [infobip/infobip-api-php-client#19]
There is nowhere indicated in the readme about how to send a message to multiple numbers. The closest to that is somewhat confusing. 
In the line below: 
```
$destination = new infobip\api\model\Destination();
$destination->setTo(TO);

$message = new infobip\api\model\sms\mt\send\Message();
$message->setFrom(FROM);
$message->setDestinations([$destination]);
```
what is passed to `$destination->setTo()`? How does one add multiple phone numbers, assuming this is supposed to handle that?

**Comment by Antolius** [comment]
Hi!

Yes, it is possible to send one SMS message to multiple phone numbers.
I've added an example illustrating this: [examples/send_sms_advanced_multiple_destinations_example.php](https://github.com/infobip/infobip-api-php-client/blob/master/infobip/examples/send_sms_advanced_multiple_destinations_example.php)
Just fill out the `$phoneNumbers` array with actual phone numbers, and messages will be sent to all of them.
You can find instructions on how to run examples in the project's [readme](https://github.com/infobip/infobip-api-php-client#running-examples).

Hope this helps!

**Comment by bot101** [comment]
Thanks @Antolius I have done just that.
