### ISSUE TITLE
Countries

### ISSUE THREAD

**Issue by thanosalexander** [infobip/infobip-api-php-client#2]
Hi..I use you library in order to sent SMS. But there is a problem when I sent messages to Kenya.inside cloud.Infobip website I can send normally but never from my application. However I can sent normally to everywhere else. I receive pending enroute status with no errors.

**Comment by anamarjanovic** [comment]
Hi,
What response did you get when you tried to send messages to Kenya from your application?

Kind regards,
Ana

**Comment by thanosalexander** [comment]
I dont receive no error

the status is anytime this

groupName: PENDING
groupId:  1
id: 7
Description: Message sent to next instance
name: PENDING_ENROUTE

**Comment by anamarjanovic** [comment]
That status means that the message is on it's way to the specified number.
You can check if it is delivered by calling `GetSentSMSLogs`.
Example can be found [here](https://github.com/infobip/infobip-api-php-client/blob/master/infobip/examples/get_sent_logs_example.php).

Kind regards,
Ana
