### ISSUE TITLE
Found an error

### ISSUE THREAD

**Issue by prodhan** [infobip/infobip-api-php-client#23]
Fatal error: Uncaught RuntimeException: SSL certificate problem: unable to get local issuer certificate in G:\webs\htdocs\smart\vendor\infobip\infobip-api-php-client\infobip\api\AbstractApiClient.php:118 Stack trace: #0 G:\webs\htdocs\smart\vendor\infobip\infobip-api-php-client\infobip\api\AbstractApiClient.php(23): infobip\api\AbstractApiClient->executeRequest('GET', 'https://api.inf...', Array) #1 G:\webs\htdocs\smart\vendor\infobip\infobip-api-php-client\infobip\api\client\GetAccountBalance.php(22): infobip\api\AbstractApiClient->executeGET('https://api.inf...', NULL) #2 G:\webs\htdocs\smart\sms.php(8): infobip\api\client\GetAccountBalance->execute() #3 {main} thrown in G:\webs\htdocs\smart\vendor\infobip\infobip-api-php-client\infobip\api\AbstractApiClient.php on line 118

**Comment by denis-cutic** [comment]
Looks like an issue with your CA certificate store, it might be outdated.
See if [this](https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate) helps you.

**Comment by jdelacruz2712** [comment]
Added to 2 new lines : 

![image](https://user-images.githubusercontent.com/7109723/37924592-f3095758-30f7-11e8-8d3b-e9763c58c2dc.png)

**Comment by tomsgad** [comment]
Why not create a PR for this, it caused me headache for 3 good days.
