### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by robilin** [infobip/infobip-api-php-client#24]
am trying to send message to multiple destinations using php as in this example

https://dev.infobip.com/send-sms/single-sms-message

$to='[\"255717222303\",\"255743475944\"]';
sample codes am using 

`  curl_setopt_array($curl, array(
            CURLOPT_URL => "https://api.infobip.com/sms/1/text/single",
            CURLOPT_SSL_VERIFYHOST=>0,
            CURLOPT_SSL_VERIFYPEER=>0,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => "{ \"from\":\"{from}\", \"to\":{$to}, \"text\":\"{$message}\" }",
            CURLOPT_HTTPHEADER => array(
                "accept: application/json",
                "authorization: Basic {$auth}",
                "content-type: application/json"
                    ),
            ));`

Does that example work?

Regards

**Comment by denis-cutic** [comment]
Hi, 

I've tried your example and it works as expected.
Can you provide me the bodies of the failing request and response?

You could also try using our PHP library as shown in the following [example](https://github.com/infobip/infobip-api-php-client/blob/master/infobip/examples/send_sms_example.php)

P.S. the "from" field value in the body is missing the dollar sign

**Comment by robilin** [comment]
Hi Thank you for support, the $to field valuable was in ``json`` and  i was adding slashes on ``json`` data that was causing problems, once I removed ``addslash``, it worked just fine. Thanks

Regards
