### ISSUE TITLE
new write for text

### ISSUE THREAD

**Issue by robilin** [infobip/infobip-api-php-client#26]
How to you create new line in php, wi would like to have formatted message sent, am using simple sms api

https://dev.infobip.com/send-sms/single-sms-message using php curl

**Comment by hkozacinski** [comment]
Hi,

You simply add \n where you need the new line to appear inside the message text. You can test this easily from the examples package of the library. I have tested it on send_sms_example.php and it works fine:

$requestBody->setText("This is\nan example\nmessage.");

If you have any further questions, feel free to ask.

Kind regards

**Comment by robilin** [comment]
This is the error am getting when trying 

{"requestError":{"serviceException":{"messageId":"BAD_REQUEST","text":"Bad request"}}}

**Comment by hkozacinski** [comment]
Hi,

you have a bug in your code when calling the send_autoreply function.
`send_autoreply($phone=null, $message=null,$flag=null,$from=null);`
This way you assigned the variables in the function call to be null, created a response with null values, and got a bad request as a result. If you remove `=null` assignments from the function call, everything should be fine.

Kind regards

**Comment by robilin** [comment]
Hi sorry i put null in this post by mistake, i also figured it out what the problem was, I was putting in space after new line character in my implementation

i.e instead of `$message="This is\nan example\nmessage";`  i was using `$message="This is \n an example \n message";`
