### ISSUE TITLE
Laravel 5.1 instalation

### ISSUE THREAD

**Issue by Zonork** [infobip/infobip-api-php-client#3]
Hi.

i try to install in my laravel 5.1 project via:  "composer require infobip/infobip-api-php-client" but that not works, [InvalidArgumentException]                                                                                                                                      
  Could not find package infobip/infobip-api-php-client at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by pducic** [comment]
Hi!
we've released 1.1.0 version, so you can avoid your minimum-stability:
https://packagist.org/packages/infobip/infobip-api-php-client
