### ISSUE TITLE
Send multiple messages to multiple numbers

### ISSUE THREAD

**Issue by pedmindset** [infobip/infobip-api-php-client#30]
wanted to find out, if its possible to pass an array to setText() on the Message Class when sending to multiple number so the first number receives the first message in the message array..

if not possible, how do i implement this since its in your http api docs

**Comment by Antolius** [comment]
Hi!

You can use the [SendMultipleTextualSmsAdvanced](https://github.com/infobip/infobip-api-php-client/blob/master/infobip/api/client/SendMultipleTextualSmsAdvanced.php#L22) client. It accepts request model which allows you to specify a [list of messages](https://github.com/infobip/infobip-api-php-client/blob/master/infobip/api/model/sms/mt/send/textual/SMSAdvancedTextualRequest.php#L16), each with its own destination number and message text.

For more info on the advanced SMS endpoint see [API documentation](https://dev.infobip.com/send-sms/fully-featured-text-message).

**Comment by pedmindset** [comment]
Thanks for the response, I get it now so rather than use the setDestinations, i use setTo and create  a message array.. like so

` public function __construct($from, $contents)
    {
        $this->client = new SendMultipleTextualSmsAdvanced(new BasicAuthConfiguration(config('infobip.username'), config('infobip.password')));

        $this->requestBody = new SMSAdvancedTextualRequest();
        $this->requestBody->setMessages($this->messages($contents));

        // Executing response
        $this->response = $this->client->execute($this->requestBody);
    }

    /**
     * Creates message object for each phone number and text in the array
     *
     * @param array $content
     * @return infobip\api\model\sms\mt\send\Message 
     */
    private function messages($contents)
    {
        //A message object is created for each phone number:
        $messages = array();
        foreach ($contents as $content) {
            //Set Message array
            $message = new Message();
            $message->setFrom($content['from']);
            $message->setTo($content['to']);
            $message->setText($content['text']);
        
            $messages[] = $message;
        }
        return $messages;
    }`
