### ISSUE TITLE
Upgrade netresearch/jsonmapper

### ISSUE THREAD

**Issue by gnumoksha** [infobip/infobip-api-php-client#31]
The version of package `netresearch/jsonmapper` required by this project is `0.9.0` which is too old. The version 1.0 was [launched in 2016](https://github.com/cweiske/jsonmapper/releases).

Currently, I need at least version 1.0 in order to install [psalm](https://github.com/vimeo/psalm).

**Comment by Bu4ak** [comment]
Same issue.

Please upgrade netresearch/jsonmapper to 1.6

**Comment by dario-ib** [comment]
Hi, upgraded netresearch/jsonmapper.
If our further assistance is required, we are at disposal.
