### ISSUE TITLE
[InvalidArgumentException]                                                      Could not find a version of package aryelds/yii2-sweet-alert matching your      minimum-stability (stable). Require it with an explicit version constraint      allowing its desired stability.

### ISSUE THREAD

**Issue by poovizhi796** [infobip/infobip-api-php-client#37]
Hi,
  I have received this error. while using composer require 
  **composer require aryelds/yii2-sweet-alert**

[InvalidArgumentException]                                                   
  Could not find a version of package aryelds/yii2-sweet-alert matching your   
  minimum-stability (stable). Require it with an explicit version constraint   
  allowing its desired stability.

I tried this to composer update,
 but error,

- Installation request for aryelds/yii2-sweet-alert @dev -> satisfiable by aryelds/yii2-sweet-alert[dev-master].
    - aryelds/yii2-sweet-alert dev-master requires bower-asset/sweetalert 1.1.3 -> no matching package found.

**Comment by ivan-letenko** [comment]
Hi,
In the last release, we vastly changed and modernized this library.
This problem no longer seems relevant.
Feel free to open issues on the repository for any issue or feature request.
