### ISSUE TITLE
Issue with sending

### ISSUE THREAD

**Issue by thanosalexander** [infobip/infobip-api-php-client#4]
I have two issues.
when i send a schedule sms..(except the fact that id doesnt work if i put Datetime object in sendAt() function but only if i put tha date as atomstring format as i use Carbon for this!)
Then It sends normally the sms and i receive pending status..when it comes the time to send everytime, i receive this status! Why do i receive this?
groupName: REJECTED
groupId: 5
name: REJECTED_DESTINATION_NOT_REGISTERED	
description: Destination not registered	
statusId: 18

Also there is one more issue with wap;
when i sent the sms as wap i receive this status
groupId:1
groupName: PENDING
name: PENDING_ENROUTE
descriptions: Message sent to next instance		
statusId: 7

but after i few it changes to this status

groupName: UNDELIVERABLE	
groupId: 2	
name: UNDELIVERABLE_REJECTED_OPERATOR	
description: Message rejected by operator		
statusId: 4

why does this happen?
Also i receive push sms as normal text sms(the same with flash sms) and i set correctly the required fields

**Comment by anamarjanovic** [comment]
Hi,

did you ever top up your credit? In case you didn't, you are only allowed to send SMS to one number you registered during sign up. Trying to send a scheduled message to a different number would result in `REJECTED_DESTINATION_NOT_REGISTERED` status.

Regarding wap - what field did you set? Wap is not supported by this api.

**Comment by cedkoffeto** [comment]
can we change this registered number or add another one?

**Comment by muhammad-attaullah** [comment]
[here](https://www.infobip.com/docs/essentials/free-trial#register-multiple-numbers-and-emails) you can do more than that.

**Comment by Pytoolbox** [comment]
Hi I am having issue. I have added the free one whatsapp gives me and i even bought one on infobip.

but my messages say PENDING_ENROUTE but never go through.

I neeed help. I now have two number at 250 conv. Am i missing something. After a while says this


![Image](https://github.com/user-attachments/assets/78c13eb4-1641-46a3-8a9d-0edb386b3fb3)

**Comment by yithanglee** [comment]
in case anyone hits with 7009, i solved mine with setting the correct language settings. en_US

**Comment by raoharis111** [comment]
did anyone solve the 7009 MEDIA_TEMPLATE error
