### ISSUE TITLE
Please upgrade jsonmap

### ISSUE THREAD

**Issue by karajanchang** [infobip/infobip-api-php-client#40]
It will occur errors in php7.4, please upgrade it. Thank you.

**Comment by dario-ib** [comment]
Hi, upgraded netresearch/jsonmapper.
If our further assistance is required, we are at disposal.

**Comment by czarkom** [comment]
Can you please upgrade it again? 

jsonmapper 3.1.1 does not work with PHP 8 because `Object::getClass()` method has been deprecated, version 4.* solves this issue.
