### ISSUE TITLE
Class 'Configuration' not found

### ISSUE THREAD

**Issue by mesahach** [infobip/infobip-api-php-client#44]
i keep getting this error "Class 'Configuration' not found" even after adding the path above like this 
require __DIR__ . "/to the path/vendor/autoload.php";

**Comment by josipk-ib** [comment]
Hello mesahach,
are you using composer for dependency management? Also, can you post us a code sample to check your usage?

**Comment by mesahach** [comment]
yes i use composer for dependency management.
`<?php
require __DIR__ . '/includes/vendor/autoload.php';

$configuration = (new Configuration())
    ->setHost('https://19p319.api.infobip.com')
    ->setApiKeyPrefix('Authorization', 'App')
    ->setApiKey('Authorization', 'my api key');

$client = new GuzzleHttp\Client();

$sendSmsApi = new SendSMSApi($client, $configuration);
$destination = (new SmsDestination())->setTo('my number');
$message = (new SmsTextualMessage())
    ->setFrom('sms sender ID')
    ->setText('This is a dummy SMS message sent using infobip-api-php-client')
    ->setDestinations([$destination]);
$request = (new SmsAdvancedTextualRequest())
    ->setMessages([$message]);

try {
    $smsResponse = $sendSmsApi->sendSmsMessage($request);
} catch (Throwable $apiException) {
    // HANDLE THE EXCEPTION
}`

here is the error message:
Fatal error: Uncaught Error: Class 'Configuration' not found in C:\xampp\htdocs\path_\testsms.php:4 Stack trace: #0 {main} thrown in C:\xampp\htdocs\path_\testsms.php on line 4

**Comment by josipk-ib** [comment]
Importing `Configuration` and other used models should resolve your issue as shown below. 
`
use GuzzleHttp;  
use Infobip\Configuration;  
use Infobip\Api\SendSmsApi;  
use Infobip\Model\SmsTextualMessage;  
use Infobip\Model\SmsDestination;  
use Infobip\Model\SmsAdvancedTextualRequest;  
$client = new GuzzleHttp\Client();

$sendSmsApi = new SendSMSApi($client, $configuration);
$destination = (new SmsDestination())->setTo('my number');
...
`

**Comment by mesahach** [comment]
Worked, thanks
