### ISSUE TITLE
v3 locked to Guzzle ^6.5

### ISSUE THREAD

**Issue by OnekO** [infobip/infobip-api-php-client#45]
V3 of your package has guzzlehttp/guzzle: ^6.5 as dependency, so it's not usable if you have already an upper version of guzzle.

Should be possible to update that dependency to something greater than 6.5?

**Comment by kiselica-aldin** [comment]
Hey @OnekO :) 

we actually had that discussion even prior to releasing this version, unluckily for you we agreed to keep it at 6.5.5 at that point.

Let us walk through it again and cross-verify whether we are using any of the deprecated v6.x.x options or we are free to go with v7.x.x without making breaking changes within the lib. :)

As I understood, this is blocking you from using the lib at all?
Have you maybe tried running with overriding our guzzle and running by using v7 only?

**Comment by OnekO** [comment]
We are using v2.x, but as it looks like there is a huge improvement in v3, we were thinking about an upgrade. But not possible, ATM. 

We will wait a bit :)

**Comment by musab-olurode** [comment]
Hello. Just wanted to know if there's any update on this. Thanks.

**Comment by ib-fsrnec** [comment]
Hi @musab-olurode @OnekO, did you have a chance to take a look at the following release: https://github.com/infobip/infobip-api-php-client/releases/tag/3.1.0? I hope that solved your issue. I'm closing the issue, feel free to reach us again if needed. Thank you once again for reporting it.
