### ISSUE TITLE
account not provisioned for global one- or two-way sms (code 592)

### ISSUE THREAD

**Issue by sionnaouattara** [infobip/infobip-api-php-client#49]
Hi there. I use the infobip API for sending sms. During my sending tests, I used a Swiss number as the recipient and this is the message I received: "account not provisioned for global one- or two-way sms (code 592)". Could someone explain the problem to me? Thanks

**Comment by ibirogar** [comment]
Hi.

Please contact [support@infobip.com](mailto:support@infobip.com) regarding this particular issue as it's not an issue in the client itself.

Thank you.
