### ISSUE TITLE
Integration with Laravel

### ISSUE THREAD

**Issue by cliffordy** [infobip/infobip-api-php-client#5]
Hello,

Am glad i found the API, Can you please help me integrate it with Laravel? I have tried all invain, Please, your help will be so appreciated.

**Comment by anamarjanovic** [comment]
For using Infobip API PHP client, you have to add the following to your `composer.json` file:
```
"require": {
    "infobip/infobip-api-php-client": "dev-master"
}
```
and run `composer install` command inside your project's root folder.

You can also check out this [php tutorial](http://www.infobip.com/en/blog/step-by-step-sms-api-php-tutorial-create-your-new-web-app). It can help you with initial steps.

**Comment by cliffordy** [comment]
Thank you very much. It is very helpful!

**Comment by mostakphoenixsoftbd** [comment]
Hi anamarjanovic 
Very helpful tutorial.
