### ISSUE TITLE
ObjectSerializer::sanitizeForSerialization undefined method call

### ISSUE THREAD

**Issue by sasa-b** [infobip/infobip-api-php-client#50]
When I copy paste your example from the interactive IDE `https://tryapi.infobip.com/send-sms-php-lib` which is using the `SmsAdvancedTextualRequest` into my project I get this undefined method call on the `ObjectSerializer` error, and when you go to that class there is truly no method with that name defined.

This is the part that triggers the error in `SendSmsApi`
```php
  // for model (json/xml)
  if (isset($smsAdvancedTextualRequest)) {
        if ($headers['Content-Type'] === 'application/json') {
            $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($smsAdvancedTextualRequest));
        } else {
            $httpBody = $smsAdvancedTextualRequest;
        }
   ....     
```

Looks like this method was present in version 4.0 https://github.com/infobip/infobip-api-php-client/blob/4.0.0/Infobip/ObjectSerializer.php and it got removed in 5.0. 

My environment is:
PHP 8.2
Symfony 6.2
Dockerized in PHP-FPM alpine image
Infobip client version 5.0

===========
UPDATE:

All of these method calls will cause the undefined error as well, they are just a couple of lines bellow in the same class, looks like you removed them from the `Configuration` object:

```php
// this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
```

**Comment by fegianelli** [comment]
same problem here

**Comment by ibirogar** [comment]
Hi.

We're working on updating the examples in the interactive IDE which should then reflect the latest library version.

Meanwhile please check the README in the latest version (5.0) for up-to-date, relevant examples.

Thank you

**Comment by sasa-b** [comment]
@ibirogar I'm going to re-try the examples from the readme, but if I recall correctly they didn't work either, you still call undefined methods in the code path of execution

**Comment by ibirogar** [comment]
You're probably using an obsolete API class. It's in our backlog to clean them up.
The one you need is called "**SmsApi**".

**Comment by sasa-b** [comment]
@ibirogar Thank you! Will try it out!

**Comment by ibirogar** [comment]
Obsolete code (API classes and models) were removed in release 5.1.0.
