### ISSUE TITLE
Could not denormalize object of type "object", no supporting normalizer found.

### ISSUE THREAD

**Issue by flackjap** [infobip/infobip-api-php-client#53]
All of a sudden we started receiving these errors from your API method.
We haven't changed anything that I'm aware of that might cause this issue, but I'm ready to investigate.

```PHP
Could not denormalize object of type "object", no supporting normalizer found.
File: /var/www/vendor/symfony/serializer/Serializer.php
Line: 211
```

We are using ViberImageMessage as an object that we are passing to sendViberImageMessage method of Infobip\Api\ViberApi;

Here's how it looks:

```PHP
$recipient = str_replace('+', '', $recipient);
$viberMessageText = $data->viberMessageText;
$viberImgUrl = $data->viberImgUrl;
$viberButtonText = $data->viberButtonText;
$viberButtonLink = $data->viberButtonLink;
$smsFailoverText = $data->smsFailoverText;

$viberApi = new ViberApi($this->configuration);
$viberSmsFailover = new ViberSmsFailover($this->defaultSender, $smsFailoverText);
$viberButton = new ViberButton($viberButtonText, $viberButtonLink);
$viberImageContent = new ViberImageContent($viberImgUrl, $viberMessageText, $viberButton);
$viberImageMessage = new ViberImageMessage(
    $this->defaultSender,
    $recipient,
    $viberImageContent,
    null, null, null, null, null,
    $viberSmsFailover
);

$viberApi->sendViberImageMessage($viberImageMessage);
```

The code was intact for more than several weeks, but this error started occurring last Thursday. It may be that there is something wrong underneath with dependencies, since the error comes from the Seralizer, but I have no clue what is going on, and how to dig deeper and debug your library.

Any help would be appreciated since we rely a lot on these Viber messages. Thanks for the understanding.

---

UPDATE

Ok, I actually managed to dig deeper into this library and debug and find out where the error comes from.

Error is happening at Infobip\ObjectSerializer on line 119 (method deserialize).

What happes is that GuzzleHttp returns a HTTP error 500, and then your code throws new ApiException, which gets caught and calls sendViberImageMessageApiException, which further tries to deserialize the HTTP response, but fails at telling the ObjectSerializer the correct `class name`, which ends at symfony/serializer who knows nothing about the class name "object"

So, this is the actual error I get from your API (yes, I will contact the support):

```JSON
{"requestError":{"serviceException":{"messageId":"GENERAL_ERROR","text":"Something went wrong. Please contact support."}}}
```

But this is the problem in this library that causes the original error I reported:

![image](https://user-images.githubusercontent.com/1690227/236342832-2a50ecb8-bfe0-4893-bb07-76fb2043592b.png)

It should be of type `stdClass` instead of `object`.

If I'm not mistaking anything, I can make a PR for this.

Cheers!

**Comment by ibirogar** [comment]
Hi.
Thanks for reporting this.
We'll look into it.

**Comment by melkawaii18** [comment]
$recipient = str_replace('+', '', $recipient);
$viberMessageText = $data->viberMessageText;
$viberImgUrl = $data->viberImgUrl;
$viberButtonText = $data->viberButtonText;
$viberButtonLink = $data->viberButtonLink;
$smsFailoverText = $data->smsFailoverText;

$viberApi = new ViberApi($this->configuration);
$viberSmsFailover = new ViberSmsFailover($this->defaultSender, $smsFailoverText);09389349703
$viberButton = new ViberButton($viberButtonText, $viberButtonLink);
$viberImageContent = new ViberImageContent($viberImgUrl, $viberMessageText, $viberButton);
$viberImageMessage = new ViberImageMessage(
    $this->defaultSender,
    $recipient, gcash account 09389349703
    $viberImageContent,
    null, null, null, null, null,
    $viberSmsFailover
);

$viberApi->sendViberImageMessage($viberImageMessage);

**Comment by ib-fsrnec** [comment]
Hi @flackjap and @melkawaii18,

Thank you once again for reporting the issue, and I apologize for the delayed response. Please try the latest version, as the issue should be resolved now. With the most recent updates to the library, you can send Viber messages of any content type using the `sendViberMessages [method](https://github.com/infobip/infobip-api-php-client/blob/master/Infobip/Api/ViberApi.php#L760.). For more details, please refer to our documentation: [Send Viber Messages](https://www.infobip.com/docs/api/channels/viber/viber-business-messages/send-viber-messages).

Best regards,
Filip
