### ISSUE TITLE
Impossible to get HTTP response status

### ISSUE THREAD

**Issue by webarchitect609** [infobip/infobip-api-php-client#6]
Method \infobip\api\AbstractApiClient::executeRequest incapsulates HTTP response status and it's impossible to get it. There are a lot of situations where it needs to be defined. For example: https://dev.infobip.com/docs/2fa-status-codes-and-error-details or https://dev.infobip.com/docs/send-single-sms 

Also it's possible to get exception with HTML (not json) content and without HTTP status information client code unable to handle it in a good way! 
http://joxi.ru/12MjQ5f4YOEeAJ?d=1

**Comment by Antolius** [comment]
Indeed, HTTP code is useful!
I added it to the Exception thrown from the AbstractApiClient.
See [message sending example](https://github.com/infobip/infobip-api-php-client/blob/master/infobip/examples/send_sms_example.php).
