### ISSUE TITLE
Depracated Dependency breaking SMS capability

### ISSUE THREAD

**Issue by stefanomartinengo** [infobip/infobip-api-php-client#64]
I am unable to use the SmsApi due to the libraries dependencies being depracated. In particular, the AnnotationLoader.
When I try to use it I get an error that states: "Since symfony/serializer 6.4: The \"Symfony\\Component\\Serializer\\Mapping\\Loader\\AnnotationLoader\" class is deprecated, use \"Symfony\\Component\\Serializer\\Mapping\\Loader\\AttributeLoader\" instead."

This is making this entire library completely unusable for us. Please update this.

**Comment by ib-plivaja** [comment]
Hi @stefanomartinengo!

We are going to update the dependency.

Thank you for for reaching us and using our library.

Kind regards,
Petra
