### ISSUE TITLE
error installing composer

### ISSUE THREAD

**Issue by ryanpagaduan24** [infobip/infobip-api-php-client#7]
Command: composer install

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package infobip-api-php-client could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

C:\xampp\htdocs\api_sms>

**Comment by denis-cutic** [comment]
Hi,

can you please check if you are requiring "**infobip/**infobip-api-php-client" or just "infobip-api-php-client"?
I was able to reproduce the error only when requiring the second one, which is an incorrect package definition.

**Comment by ryanpagaduan24** [comment]
infobip-api-php-client

**Comment by denis-cutic** [comment]
Hi,

could you try creating a dummy folder and a composer.json file (inside the folder) with the following content:

`{
  "name": "my/composer-test",
  "description": "Composer-test",
  "version": "1.0.0",
  "minimum-stability": "dev",
  "require": {
    "infobip/infobip-api-php-client": "dev-master"
  }
}
`

Try running `composer install` inside the folder.
What output do you get?

Kind regards,

**Comment by ryanpagaduan24** [comment]
Hi Sir
this is the output 

Command: composer install

Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing netresearch/jsonmapper (v0.9.0)
    Downloading: 100%

  - Installing infobip/infobip-api-php-client (dev-master ce07e9a)
    Cloning ce07e9a55b9f0cb020b8dd80a882e0ed38c456b8

Writing lock file
Generating autoload files

C:\xampp\htdocs\sample_sms>

**Comment by denis-cutic** [comment]
Hi,

this means that the php client was fetched correctly.
There must be a problem with your composer.json file.
If you provide us your file we might be able to help you solve the problem. 

Kind regards,

**Comment by ryanpagaduan24** [comment]
`{
  "name": "infobip/infobip-api-php-client",
  "description": "Infobip SMS library for PHP",
  "version": "1.1.2",
  "keywords": [
    "infobip",
    "sms",
    "hlr",
    "msisdn",
    "api"
  ],
  "homepage": "http://dev.infobip.com",
  "authors": [
    {
      "name": "",
      "email": "libraries@infobip.com"
    }
  ],
  "support": {
    "email": "support@infobip.com"
  },
  "license": "Apache-2.0",
  "minimum-stability": "dev",
  "require": {
    "infobip-api-php-client": "dev-master"
},
  "autoload": {
    "psr-4": {
      "infobip\\api\\": "infobip/api/",
      "infobip\\api\\client\\": "infobip/api/client/",
      "infobip\\api\\configuration\\": "infobip/api/configuration/",
      "infobip\\api\\model\\": "infobip/api/model/",
      "infobip\\api\\model\\sms\\": "infobip/api/model/sms/",
      "infobip\\api\\model\\sms\\mo\\": "infobip/api/model/sms/mo/",
      "infobip\\api\\model\\sms\\mo\\logs\\": "infobip/api/model/sms/mo/logs/",
      "infobip\\api\\model\\sms\\mo\\reports\\": "infobip/api/model/sms/mo/reports/",
      "infobip\\api\\model\\sms\\mt\\": "infobip/api/model/sms/mt/",
      "infobip\\api\\model\\sms\\mt\\logs\\": "infobip/api/model/sms/mt/logs/",
      "infobip\\api\\model\\sms\\mt\\reports\\": "infobip/api/model/sms/mt/reports/",
      "infobip\\api\\model\\sms\\mt\\send\\": "infobip/api/model/sms/mt/send/",
      "infobip\\api\\model\\sms\\mt\\send\\binary\\": "infobip/api/model/sms/mt/send/binary/",
      "infobip\\api\\model\\sms\\mt\\send\\textual\\": "infobip/api/model/sms/mt/send/textual/",
      "infobip\\api\\model\\nc\\": "infobip/api/model/nc/",
      "infobip\\api\\model\\nc\\logs\\": "infobip/api/model/nc/logs/",
      "infobip\\api\\model\\nc\\notify\\": "infobip/api/model/nc/notify/",
      "infobip\\api\\model\\nc\\query\\": "infobip/api/model/nc/query/",
      "infobip\\api\\model\\account\\": "infobip/api/model/account/"
    }
  }
}`

**Comment by denis-cutic** [comment]
Hi,

the problem is that you are using the infobip-api-php-client's composer.json.
You should create a composer.json file inside your project and then in the require section add `"infobip/infobip-api-php-client": "dev-master"`.

Kind regards

**Comment by ryanpagaduan24** [comment]
Ok sir thank's
