### ISSUE TITLE
is there a way of sending sms using account key only 

### ISSUE THREAD

**Issue by ryanpagaduan24** [infobip/infobip-api-php-client#8]
hello sir

i create a new system that can sent sms using your api
with username and password 
is there a way of sending sms using account key
i create a sub account and i want to sent sms using that account to validate the parent account 
but the main problem is that i can't sent sms cus the parent password encrypt  to md5 into my database

the parent username and password is the same to user db account

hope my english !!

**Comment by denis-cutic** [comment]
Hi,

here ([link](https://dev.infobip.com/docs/settings-introduction)) you can find the API for managing sub accounts and their API keys.

Hope that helps,
Kind regards
